import assert from "node:assert/strict";
import { calculateSag, parseSagInput, suggestSag } from "../src/lib/sag";
import { findSagReference, sagReferences } from "../src/data/sag-references";

assert.deepEqual(calculateSag(140, 20, 28), { targetMm: 28, measuredPercent: 20, differenceMm: 0 });
assert.deepEqual(calculateSag(55, 30, 16.5), { targetMm: 16.5, measuredPercent: 30, differenceMm: 0 });
assert.equal(calculateSag(100, 20, 0).measuredPercent, 0);
assert.equal(calculateSag(100, 20).measuredPercent, undefined);
assert.equal(calculateSag(100, 20, 30).differenceMm, 10);
for (const length of [0, -1, NaN, Infinity]) assert.ok(calculateSag(length, 20).error);
for (const target of [0, -1, 100, NaN, Infinity]) assert.ok(calculateSag(100, target).error);
for (const measured of [-1, 101, NaN, Infinity]) assert.ok(calculateSag(100, 20, measured).error);
assert.equal(parseSagInput("16,5"), 16.5);
assert.ok(Number.isNaN(parseSagInput(" ")));
assert.ok(Number.isNaN(parseSagInput("abc")));
console.log("SAG: conversiones y validación correctas.");
assert.equal(suggestSag("xc", false).value, 22.5);
assert.equal(suggestSag("trail", true).value, 27.5);
assert.equal(suggestSag("enduro", false).value, 30);
assert.equal(suggestSag("dh", false, findSagReference("FOX", "36 · 2024", false, "air")).value, 17.5);
assert.equal(suggestSag("xc", true, findSagReference("FOX", "FLOAT DPS · 2018", true, "air")).value, 27.5);
assert.equal(suggestSag("unknown", false).value, 20);
assert.equal(suggestSag("xc", false).verified, false);
assert.equal(suggestSag("xc", false, findSagReference("FOX", "36 · 2024", false, "air")).verified, true);
assert.equal(findSagReference("FOX", "36 · 2024", false, "coil"), undefined);
assert.equal(findSagReference("FOX", "FLOAT X2 · 2025", false, "air"), undefined);
assert.equal(suggestSag("xc", true, findSagReference("FOX", "FLOAT X2 · 2025", true, "air")).value, 30);
assert.equal(suggestSag("xc", false, findSagReference("SR Suntour", "DUROLUX38 EQ · guía 2022", false, "air")).value, 30);
assert.equal(suggestSag("dh", false, findSagReference("RockShox", "ZEB · DebonAir+", false, "air")).verified, false);
assert.equal(suggestSag("dh", false, findSagReference("RockShox", "ZEB · DebonAir+", false, "air")).range, null);
for (const item of sagReferences) {
  assert.ok(item.url.startsWith("https://"));
  if (item.range) assert.ok(item.range[0] > 0 && item.range[0] <= item.range[1] && item.range[1] < 100);
}
assert.equal(new Set(sagReferences.map(item => `${item.brand}:${item.label}:${item.rear}`)).size, sagReferences.length);
console.log(`${sagReferences.length} referencias oficiales: alcance y objetivos OK.`);
assert.equal(suggestSag("unknown", false, findSagReference("Öhlins", "RXF38 m.2 Air · manual m.2", false, "air")).value, 12.5);
assert.equal(suggestSag("unknown", false, findSagReference("Öhlins", "RXF38 m.2 Coil · manual m.2", false, "coil")).value, 17.5);
assert.equal(findSagReference("Öhlins", "RXF38 m.2 Air · manual m.2", false, "coil"), undefined);
assert.equal(suggestSag("unknown", true, findSagReference("DVO", "Topaz Prime · guía 2.1 / 2024", true, "air")).value, 25);
assert.equal(suggestSag("unknown", false, findSagReference("FOX", "Podium · 2026", false, "air")).value, 17.5);
assert.equal(suggestSag("unknown", false, findSagReference("Manitou", "Mattoc Pro Gen 3 · guía 2023", false, "air")).value, 22.5);
assert.equal(suggestSag("unknown", false, findSagReference("Marzocchi", "Super Z · guía Rev. B / 2024", false, "air")).value, 17.5);
assert.equal(suggestSag("unknown", false, findSagReference("RockShox", "SID Ultimate 2P · D1 / DebonAir+", false, "air")).verified, false);
