"use client";


import Link from "next/link";
import { useState, useEffect, useRef } from "react";
import { ServiceIcon } from "@/components/ServiceIcon";
import { serviceVisual, serviceBenefits } from "@/lib/service-visuals";
import { suggestedExtras } from "@/lib/quote-presentation";
import { formatCLP } from "@/lib/format";
import { matchesSearch } from "@/lib/catalog-search";
import { pricingCatalog, includingService, coveringPackage, packageLeaves, selectedLeaves, supportsVehicle, type QuoteVehicle, type Vehicle, type PackageService, type Selection } from "@/lib/package-quote";
import { packageReference } from "@/lib/package-reference";
export type PackageCatalog = { slug:string; name:string; services:(PackageService & { summary?:string|null })[] }[];
export function PackageSelector({catalog,selection,vehicle,doubleSuspension,vehicles,query,covered,onToggle,onVehicle,onQuery,mode="principal"}: {mode?:"principal"|"extras";catalog:PackageCatalog;selection:Selection;vehicle:Vehicle;doubleSuspension:boolean;vehicles:QuoteVehicle[];query:string;covered:string[];onToggle:(slug:string)=>void;onVehicle:(v:Vehicle,doubleSuspension:boolean)=>void;onQuery:(q:string)=>void}) {
  const raw=catalog.flatMap(c=>c.services);const all=pricingCatalog(raw);const [showIndividuals,setShowIndividuals]=useState(selection.manual.length>0&&selection.packages.length===0);const visibleCatalog=catalog.map(c=>({...c,services:pricingCatalog(c.services)})); const leaves=selectedLeaves(all,selection);
  const packages=all.filter(s=>s.kind === "package" && s.individuallySelectable && supportsVehicle(s,vehicle,doubleSuspension));
  const included=new Set([...selection.packages,...selection.manual].flatMap(slug=>packageLeaves(all,slug)));
  const price=(s:PackageService)=>s.price===null?"A cotizar":(s.priceFrom?"Desde ":"")+formatCLP(s.price);
  const [extraSlugs,setExtraSlugs]=useState<string[]>([]);
  const rail=useRef<HTMLDivElement>(null);
  const [railPosition,setRailPosition]=useState({start:true,end:false});
  const packKey=selection.packages.join("|");
  useEffect(()=>{if(mode==="extras"){setExtraSlugs(suggestedExtras(raw,[...selection.packages,...selection.manual],leaves,vehicle).map(s=>s.slug));setRailPosition({start:true,end:false});rail.current?.scrollTo({left:0});}},[mode,vehicle,packKey]);
  const extras=extraSlugs.map(slug=>all.find(s=>s.slug===slug)).filter((s):s is typeof all[number]=>!!s&&s.active&&!s.removed&&supportsVehicle(s,vehicle));
  return <fieldset className="tp-fieldset"><legend className="tp-label">{mode==="principal"?"Escoge tu vehículo y servicio principal":"¿Quieres agregar algo más?"}</legend>
    {mode==="principal"&&<div className="tp-options tp-options-2">{vehicles.map(option=><label key={option.slug} className="tp-option"><input type="radio" name="vehicleType" value={option.slug} checked={vehicle===option.slug} onChange={()=>onVehicle(option.slug,false)}/><span>{option.name}</span></label>)}</div>}
    {!vehicles.length && <p className="tp-alert">No hay vehículos disponibles para cotizar en este momento.</p>}
    {mode==="principal"&&packages.length>0&&<div className="tp-selection-mode"><button type="button" className="tp-btn tp-btn-secondary tp-btn-sm" aria-pressed={!showIndividuals} onClick={()=>setShowIndividuals(false)}>Elegir un pack</button><button type="button" className="tp-btn tp-btn-secondary tp-btn-sm" aria-pressed={showIndividuals} onClick={()=>setShowIndividuals(true)}>Prefiero servicios individuales</button></div>}
    {mode==="principal"&&!showIndividuals&&packages.length>0 && <div><h2 className="tp-quote-heading">Paquetes de servicios</h2><div className="tp-package-grid">{packages.map(s=>{const parent=coveringPackage(all,selection,s.slug);const chosen=selection.packages.includes(s.slug);const ref=packageReference(all,s);return <div key={s.slug} className={"tp-package-option"+(parent?" is-included":chosen?" is-selected":"")}><label className="tp-option">{!parent&&<input type="checkbox" checked={chosen} onChange={()=>onToggle(s.slug)} />}<span><strong>{s.name}</strong>{parent?<small className="tp-pack-inclusion" role="status">Incluido en {parent.name} · Sin cobro adicional</small>:<b>{price(s)}</b>}{!parent&&ref&&<small>Valor individual{ref.estimated?" referencial":""}: {formatCLP(ref.reference)}{ref.savings!==null&&<> · {ref.savings<0?"Diferencia":"Ahorro"}: {formatCLP(Math.abs(ref.savings))}</>}</small>}{s.summary && <small>{s.summary}</small>}<small>{s.components.length?`${packageLeaves(all,s.slug).length} trabajos incluidos`:"Composición pendiente · se cotiza por separado"}</small></span></label>{s.components.length>0&&<details className="tp-pack-details"><summary>Ver servicios incluidos</summary><ul>{packageLeaves(all,s.slug).map(slug=><li key={slug}>{all.find(c=>c.slug===slug)!.name}</li>)}</ul></details>}</div>})}</div></div>}
    {mode==="extras"&&<><p className="tp-hint">Opcional. Añade solo lo que necesites; el total se actualiza al instante.</p>{extras.length>0&&<section className="tp-extra-showcase" aria-label="Complementa tu mantención"><div className="tp-extra-heading"><h3>Complementa tu mantención</h3><span>Opciones para tu {vehicles.find(v=>v.slug===vehicle)?.name.toLocaleLowerCase()}</span></div><div ref={rail} className="tp-extra-grid" tabIndex={0} aria-label="Servicios opcionales, desliza para explorar" onScroll={e=>{const el=e.currentTarget;setRailPosition({start:el.scrollLeft<2,end:el.scrollLeft+el.clientWidth>=el.scrollWidth-2});}}>{extras.map(s=>{const selected=leaves.includes(s.slug);const parent=includingService(all,selection,s.slug);const locked=!!parent||selection.packages.some(slug=>packageLeaves(all,slug).includes(s.slug));return <article className={"tp-extra-card"+(selected?" is-added":"")} key={s.slug}><div className="tp-extra-art"><ServiceIcon name={s.name} slug={s.slug} size={104}/><span className="tp-extra-accent"/></div><div className="tp-extra-copy"><strong>{s.name}</strong><p>{serviceBenefits[serviceVisual(s)]}</p><span className="tp-extra-price">{locked?"Incluido · Sin cobro adicional":price(s)}</span></div><button type="button" className={"tp-btn tp-btn-sm "+(selected?"tp-btn-secondary":"tp-btn-primary")} disabled={locked} aria-pressed={selected} aria-label={locked?s.name+", incluido sin cobro adicional":(selected?"Quitar ":"Añadir ")+s.name} onClick={()=>onToggle(s.slug)}>{locked?"Ya incluido":selected?"Añadido ✓ · Quitar":"+ Añadir"}</button></article>})}</div><div className="tp-extra-controls"><button type="button" aria-label="Ver opciones anteriores" disabled={railPosition.start} onClick={()=>rail.current?.scrollBy({left:-rail.current.clientWidth*.85})}>←</button><span>Desliza para ver más opciones</span><button type="button" aria-label="Ver opciones siguientes" disabled={railPosition.end||extras.length<2} onClick={()=>rail.current?.scrollBy({left:rail.current.clientWidth*.85})}>→</button></div></section>}</>}
    <details open={mode==="principal"&&(showIndividuals||!packages.length)} className="tp-individual-picker" hidden={mode==="principal"&&!showIndividuals&&packages.length>0}><summary>{mode==="extras"?"Ver todos los servicios individuales":"Servicios individuales"}</summary>
    <label className="tp-field">Buscar un servicio<input className="tp-input" type="search" value={query} onChange={e=>onQuery(e.target.value)} placeholder="Frenos, ruedas, suspensión…" /></label>
    <p className="tp-hint">Precios en pesos chilenos. Los trabajos cubiertos por un paquete no se cobran aparte.</p>
    {visibleCatalog.filter(c=>c.slug!=="retiro-entrega").map(c=>{const rows=c.services.filter(s=>s.kind!=="package" && supportsVehicle(s,vehicle,doubleSuspension) && (s.individuallySelectable||included.has(s.slug)) && matchesSearch(query,s.name,s.summary,c.name));return rows.length>0 && <div key={c.slug} id={c.slug}><h3 className="tp-quote-category">{c.name}</h3><div className="tp-options tp-options-2">{rows.map(s=>{const parent=includingService(all,selection,s.slug);return <div className={"tp-service-option"+(parent?" is-included":"")} key={s.slug}><label className="tp-option"><input type="checkbox" checked={leaves.includes(s.slug)} onChange={()=>onToggle(s.slug)} disabled={!!parent||(mode==="extras"&&covered.includes(s.slug))||(!s.individuallySelectable&&!included.has(s.slug))} /><ServiceIcon name={s.name} slug={s.slug} size={38}/><span>{s.name}<small>{parent?`Incluido en ${parent.name} · Sin cobro adicional`:covered.includes(s.slug)?"Incluido en paquete":price(s)}</small>{s.components.length>0&&<small>Incluye: {packageLeaves(all,s.slug).filter(slug=>slug!==s.slug).map(slug=>all.find(c=>c.slug===slug)?.name).join(", ")}</small>}<Link href={`/servicios/${s.slug}/`}>Ver detalle</Link></span></label></div>})}</div></div>})}
    {!catalog.some(c=>c.services.some(s=>s.kind!=="package"&&supportsVehicle(s,vehicle,doubleSuspension)&&matchesSearch(query,s.name,s.summary,c.name))) && <p>No hay servicios con esa búsqueda para este vehículo.</p>}
    </details>
  </fieldset>;
}
